name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13' # spécifie la version de Python

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt # assure-toi d'avoir ce fichier

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: connexion au registre privé
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t $DOCKER_USERNAME/my-flask-app .

      # Ajouter la condition pour que le push ne se fasse que si les tests sont réussis
      - name: Push Docker image to Docker Hub
        if: success()  # Cette étape ne s'exécute que si les tests passent
        run: |
          docker push $DOCKER_USERNAME/my-flask-app

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest

  notifications:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Send failure email
        if: failure()  # Cette étape ne s'exécute que si un test échoue
        uses: matt-actions/send-email@v1
        with:
          to: "jbferrando123@gmail.com"
          subject: "CI Pipeline Failed"
          body: "Le pipeline CI a échoué. Veuillez vérifier les tests."
